import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mi primera app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="text-4xl">
          <div className="text-xl bg-blue-400 menu">
            <a href="/">INICIO</a>
            <a href="" className="tienda">
              TIENDA
            </a>
            <a href="/blog">BLOG</a>
            <a href="/acerca">ACERCA</a>
            <a href="/registro">REGISTRO</a>
          </div>
          <div className="text-xl bg-blue-400 menu submenu">
            <a href="/tienda/decoracion">DECORACIÓN</a>
            <a href="/tienda/electronica">ELECTRÓNICA</a>
            <a href="/tienda/libros">LIBROS</a>
            <a href="/tienda/mobiliario">MOBILIARIO</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
